// re-run these query again...

// because of by user event these queries value will be change...
// & so we need to keep track of those change OR update out changed value...
// event like create, update or delete...

export const reRunQueries = [
    'getAllQuote',
    'getUserProfile',
];